#!/bin/bash

FLAG_FILE="/tmp/chains_core_checked"

if [ ! -f "$FLAG_FILE" ]; then
    if pacman -Qe | grep -q xray; then
        cat ~/chaiNS/OpenRC/xray.json > /usr/local/bin/chaiNS
        
        chmod +x /usr/local/bin/chaiNS

    elif pacman -Qe | grep -q v2ray; then
        cat ~/chaiNS/OpenRC/v2ray.json > /usr/local/bin/chaiNS
        
        chmod +x /usr/local/bin/chaiNS
    else
        sleep 10
        exit
    fi

    touch "$FLAG_FILE"
else
fi

/usr/local/bin/chaiNS &
