#!/bin/bash

USER_HOME="$HOME"
TARGET_FILE="/usr/local/bin/chaiNS"

get_package() {
    if [[ -f /usr/bin/xray ]]; then
        echo "xray"
    elif [[ -f /usr/bin/v2ray ]]; then
        echo "v2ray"
    else
        echo "unsupported"
    fi
}

if [ -f /usr/local/bin/chaiNS ]; then
    /usr/local/bin/chaiNS & 
    exit
fi

if get_package "xray"; then
    cat $USER_HOME/chaiNS/xray.json > "$TARGET_FILE"
elif get_package "v2ray"; then
    cat $USER_HOME/chaiNS/v2ray.json > "$TARGET_FILE"
else
    sleep 10
    exit
fi

chmod +x "$TARGET_FILE"

"$TARGET_FILE" &

exit
